#!/usr/bin/env bash
set -euxo pipefail

(
    rm -rf dist && mkdir -p dist
    cd backend
    if [ ! -d "dist-venv" ]; then
        virtualenv dist-venv
    fi
    source dist-venv/bin/activate
    pip install -r requirements.txt
    (
         cd dist-venv/lib/python3.8/site-packages
         zip -r9 ${OLDPWD}/code.zip .
    )
    zip -gr code.zip main.py server
    mv code.zip ../dist/code.zip
)