#!/usr/bin/env bash

set -euxo pipefail

TARGET=$1
AUTO_APPROVE_TF=${AUTO_APPROVE_TF:-false}

if [[ "$AUTO_APPROVE_TF" == "true" ]]; then
    TERRAFORM_ARGS='-auto-approve'
else
    TERRAFORM_ARGS=''
fi

(
    cd infra/$TARGET
    terraform apply $TERRAFORM_ARGS
)

set +x
FRONTEND_BUCKET=$(cd infra/$TARGET && terraform output frontendbucket)
DISTRIBUTION_ID=$(cd infra/$TARGET && terraform output cloudfront)
set -x


aws s3 sync frontend/build s3://$FRONTEND_BUCKET
aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/index.html"

