version: '2.1'

services:
  localstack:
    container_name: localstack_main
    image: "localstack/localstack:0.12.5"
    ports:
      - "4566:4566"
      - "8000:8000"
    environment:
      - SERVICES=s3,iam,dynamodb,apigateway,lambda,cloudwatchlogs,ses
      - DEBUG=1
      - PORT_WEB_UI=8000
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=nafnaval_default
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  frontend:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./infra/dev/nginx:/etc/nginx/conf.d/
    depends_on:
      - localstack
