version: '2.1'

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4567:4567"
      - "4571:4571"
      - "8080:8080"
    environment:
      - SERVICES=s3,iam,dynamodb,apigateway,lambda,cloudwatchlogs,ses
      - DEBUG=1
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"