name: CI/CD

on:
  push:
  create:
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        name: Node modules cache
        id: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install yarn packages
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: |
          cd frontend
          yarn install

      - name: Prettier frontend
        run: |
          cd frontend
          yarn prettier . --check

      - name: Test frontend
        run: |
          cd frontend
          yarn test --ci


  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r backend/requirements.txt -r backend/test-requirements.txt

      - name: Black backend
        run: |
          cd backend
          black . --check

      - name: Test backend
        run: |
          cd backend
          pytest .


  integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install virtualenv
        run: pip install virtualenv

      - uses: actions/cache@v2
        name: Node modules cache
        id: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('frontend/yarn.lock') }}

      # TODO: Re-use built artifacts for staging+prod?
      - name: Build
        run: make

      - name: Start local environment
        run: make local-env

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: cypress-${{ runner.os }}-${{ hashFiles('frontend/yarn.lock') }}

      - run: npx cypress install
        working-directory: ./frontend

      - name: Cypress run dev
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          record: true
          install: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}


  deploy:
    runs-on: ubuntu-20.04

    needs:
      - backend
      - frontend
      - integration

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set terraform version
        run: echo "TERRAFORM_VERSION=$(cat ./.terraform-version)" >> $GITHUB_ENV
      - name: Install terraform
        run: |
          mkdir -p bin
          cd bin
          curl -LO https://raw.github.com/robertpeteuil/terraform-installer/f5ea8c70b43492f6e98fa231122b0c07f305729d/terraform-install.sh
          chmod +x terraform-install.sh
          ./terraform-install.sh -i $TERRAFORM_VERSION -c
          pwd >> $GITHUB_PATH
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install virtualenv
        run: pip install virtualenv

      - name: Build
        run: make

      - name: Deploy staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          AUTO_APPROVE_TF: true
        run: make target=staging deploy


      - name: Cypress run staging
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=https://stagingwww.nafnaval.is
          working-directory: ./frontend
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          AUTO_APPROVE_TF: true
        run: make target=prod deploy