name: Staging deployment

on:
  push:
    branches:
      - 'master'


jobs:
  prepare:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy staging
        run: make target=staging deploy
